import type { Metadata } from "next";
import { daysOneFont, montserratFont } from "@/app/fonts/font";
import "./globals.css";
import NavLink from "@/components/NavLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navLinks = ["mon compte", "FAQ", "panier"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${daysOneFont.className} bg-[#F8F9E9]`}>
        <NavLink />
        {children}
      </body>
    </html>
  );
}
